name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    artifactoryUpload:
    name: Upload Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://ncr.jfrog.io/'
        user: 'username'
        password: ${{ secrets.artifact_key }}
        args: u "app.js" "https://ncr.jfrog.io/artifactory/hspre-generic-group/" --recursive=true --build-name=myawesomeapp
